name: VyOS build 1.3

permissions:
  contents: write
  
on:
  workflow_dispatch:
  schedule:
    - cron: 0 3 * * *

env:
  GIT_CLONE_URL: https://github.com/vyos/vyos-build
  BRANCH: equuleus
  ARCHITECTURE: amd64
  BUILD_BY: 8426315+akazantzidis@users.noreply.github.com
  BUILD_TYPE: release
  VERSION: 1.3
  DEBIAN_MIRROR: http://ftp.us.debian.org/debian/

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: vyos/vyos-build:equuleus
      options: --workdir /vyos --privileged

    steps:
      - name: Clone source code
        run: git clone -b $BRANCH --single-branch $GIT_CLONE_URL

      - name: Build
        working-directory: ./vyos-build
        run: |
          ./configure --architecture amd64 --build-by $BUILD_BY --build-type $BUILD_TYPE --version $VERSION-$(date +%Y%m%d%H%M)
          sudo make iso
      
      - name: Get date
        id: date
        uses: Kaven-Universe/github-action-current-date-time@v1
        with:
          format: "DD-MM-YYYY"
      
      - name: Create release and upload artifact  
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ env.VERSION }}-${{ steps.date.outputs.time }}
          files: |
            vyos-build/build/vyos-${{ env.VERSION }}-*.iso

  #cleanup_old_workflow_runs:
  #  needs: build
  #  runs-on: ubuntu-latest

  #  steps:
  #    - name: Delete old workflow runs
  #      uses: GitRML/delete-workflow-runs@main
  #      with:
  #        retain_days: 7
